<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>KL Syntax: version 1.1.1</string>
	<key>fileTypes</key>
	<array>
		<string>kl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^.*\b(inline|function|public|protected|private|operator)\s*(\w+\s*)?\([^\)]*\)(\s*\{[^\}]*)?\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~K</string>
	<key>name</key>
	<string>KL</string>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*\*(?!/)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.kl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.documentation.kl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.kl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.kl</string>
				</dict>
			</array>
		</dict>
		<key>parameter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(in|io|out)\s+([A-Z][a-zA-Z0-9_]*)\s+([a-z_][a-zA-Z0-9_]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.kl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.user.kl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.kl</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([A-Z][a-zA-Z0-9_]*)\s+([a-z_][a-zA-Z0-9_]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.user.kl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.kl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>memberName</key>
		<dict>
			<key>match</key>
			<string>\b\b</string>
		</dict>
		<key>member</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([A-Z][a-zA-Z0-9_]*)\s+([a-z_][a-zA-Z0-9_]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.kl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.memberNames.begin.kl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.kl</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string><![CDATA[\b(function|inline|public|protected|private)*\s+([a-zA-Z0-9_<>]+)\s+([A-Z_][a-zA-Z0-9_]*)\s*\.\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*([\?!]?)\s*(\()]]></string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.kl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.user.kl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.kl</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.kl</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.kl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.function.kl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(function|inline|public|protected|private)*\s+([A-Z_][a-zA-Z0-9_]*)\s*\.\s*([a-z_][a-zA-Z0-9_]*)\s*([\?!]?)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.global.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.user.kl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.kl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.kl</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.kl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.function.kl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(function|inline|public|protected|private)*\s+([a-zA-Z_][a-zA-Z0-9_]*)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.global.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.kl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.kl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.kl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.function.kl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(function|inline|public|protected|private)*\s+([A-Z_][a-zA-Z0-9_]*)\s+([A-Z_][a-zA-Z0-9_]*)\s*\.\s*([a-z_][a-zA-Z0-9_]*)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.global.kl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.kl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.kl</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.kl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.function.kl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(function|inline|public|protected|private)*\s+([A-Z_][a-zA-Z0-9_]*)\s+(\+|-|\*|/|%)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.global.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.kl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.kl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.kl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.function.kl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(function|inline|public|protected|private)*\s+([A-Z][a-zA-Z0-9_]*)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.global.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.kl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.kl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.function.kl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(function|inline|public|protected|private)*\s+(~)([A-Z][a-zA-Z0-9_]*)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.global.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.kl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.kl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.kl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.function.kl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(operator)\s+([a-z_][a-zA-Z0-9_]*)\s*(&lt;&lt;&lt;)\s*([a-z_][a-zA-Z0-9_]*)\s*(&gt;&gt;&gt;)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.global.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.kl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.parallel.kl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.kl</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.parallel.kl</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.kl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.function.kl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(function|inline|operator|public|protected|private)*\s+([a-z_][a-zA-Z0-9_]*)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.global.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.kl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.kl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.function.kl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(struct|object|interface)\s+([A-Z_][a-zA-Z0-9_]*)\s*({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.kl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})\s*;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.kl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#member</string>
				</dict>
			</array>
			<key>name</key>
			<string>meta.type.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(function|inline|operator|struct|object|interface|alias|use|require|break|case|continue|default|const|var|in|io|out|private|protected|public|do|else|for|if|use|require|return|switch|throw|while)\b</string>
			<key>name</key>
			<string>keyword.kl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.kl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z_][a-zA-Z0-9_]*)\s+(in)\b</string>
			<key>name</key>
			<string>meta.loop.in.kl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.kl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.kl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([A-Z][a-zA-Z0-9_]*)\s+([a-z_][a-zA-Z0-9_]*)\b</string>
			<key>name</key>
			<string>meta.variable.kl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>node.kl shebang</string>
			<key>match</key>
			<string>^#!/usr/bin/env kl</string>
			<key>name</key>
			<string>comment.line.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btrue\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bfalse\b</string>
			<key>name</key>
			<string>constant.language.boolean.false.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bnull\b</string>
			<key>name</key>
			<string>constant.language.null.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(this)\b</string>
			<key>name</key>
			<string>variable.language.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)([sSuU](8|16|32|64)?)?|(([0-9]+\.?[0-9]*)|(\.[0-9]+))(([sSuU](8|16|32|64)?)|(((e|E)(\+|-)?[0-9]+)?((f|F)(32|64)?)?)))?\b</string>
			<key>name</key>
			<string>constant.numeric.kl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.kl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.kl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.kl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.kl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.kl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.kl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.kl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.kl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Boolean|UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Float32|Float64|String|Container|Index|Size|Integer|Scalar)\b</string>
			<key>name</key>
			<string>support.type.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sqrt|abs|sin|cos|tan|asin|acos|atan|atan2|log|log10|exp|pow|round|floor|ceil)\b</string>
			<key>name</key>
			<string>support.function.math.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(report|setError|getError|clearError)\b</string>
			<key>name</key>
			<string>support.function.debug.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(getCurrentTicks|getSecondsBetweenTicks)\b</string>
			<key>name</key>
			<string>support.function.perf.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(GL_TRIANGLES|GL_FRONT|GL_BACK|GL_LESS|GL_NONE|GL_DEPTH_COMPONENT|GL_TEXTURE_CUBE_MAP|GL_DEPTH_STENCIL|GL_INT|GL_BOOL|GL_FLOAT_VEC2|GL_FLOAT_VEC3|GL_FLOAT_VEC4|GL_FLOAT_MAT4|GL_FLOAT_MAT3|GL_ELEMENT_ARRAY_BUFFER|GL_STATIC_DRAW|GL_UNSIGNED_INT|GL_TEXTURE_2D|GL_RGBA8|GL_RGBA|GL_UNSIGNED_BYTE|GL_NEAREST|GL_CLAMP_TO_EDGE|GL_CLAMP_TO_EDGE|GL_FLOAT|GL_ARRAY_BUFFER)\b</string>
			<key>name</key>
			<string>support.constant.opengl.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(glBindTexture|glDeleteFramebuffers)\b</string>
			<key>name</key>
			<string>support.function.opengl.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;&lt;&lt;|&gt;&gt;&gt;|\bexecuteParallel\b)</string>
			<key>name</key>
			<string>keyword.parallel.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!|%|&amp;|\*|/|\-\-|\-|\+\+|\+|~|===|==|=|!=|!==|&lt;=|&gt;=|&lt;&lt;=|&gt;&gt;=|&lt;&lt;|&gt;&gt;|&lt;|&gt;|!|&amp;&amp;|\|\||\?\:|\*=|(?&lt;!\()/=|%=|\+=|\-=|&amp;=|\^=|@</string>
			<key>name</key>
			<string>keyword.operator.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\;</string>
			<key>name</key>
			<string>punctuation.terminator.statement.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>,[ |\t]*</string>
			<key>name</key>
			<string>meta.delimiter.object.comma.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.delimiter.method.period.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>meta.brace.square.kl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;&lt;&lt;|&gt;&gt;&gt;</string>
			<key>name</key>
			<string>meta.brace.parallel.kl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.kl</string>
	<key>uuid</key>
	<string>93E017CC-6F27-11D9-90EB-000D93589AF6</string>
</dict>
</plist>
